steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install', '--legacy-peer-deps']

  - name: node:$_NODE_VERSION
    entrypoint: npx
    args: ['nx', 'build', 'web', '--prod']
    env:
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'
      - 'NEXT_PUBLIC_X_API_KEY=${_NEXT_PUBLIC_X_API_KEY}'
      - 'NEXT_PUBLIC_BOT_ID=${_NEXT_PUBLIC_BOT_ID}'
      - 'NEXT_PUBLIC_DISCORD_AUTH_URL=${_NEXT_PUBLIC_DISCORD_AUTH_URL}'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env', 'dist/apps/web/.env.local']
    env:
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'
      - 'NEXT_PUBLIC_X_API_KEY=${_NEXT_PUBLIC_X_API_KEY}'
      - 'NEXT_PUBLIC_BOT_ID=${_NEXT_PUBLIC_BOT_ID}'
      - 'NEXT_PUBLIC_DISCORD_AUTH_URL=${_NEXT_PUBLIC_DISCORD_AUTH_URL}'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: COPY-STUFF
    entrypoint: bash
    args:
      - '-e'
      - '-c'
      - |
        cp apps/web/app.yaml dist/apps/web/app.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
    dir: 'dist/apps/web'

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" --service="default" | tail -n +40 | xargs -r gcloud app versions delete --quiet

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
