steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install', '--legacy-peer-deps']

  - name: node:$_NODE_VERSION
    entrypoint: npx
    args: ['nx', 'build', 'tg-web', '--prod']
    env:
      - 'VITE_BOT_USERNAME=${_VITE_BOT_USERNAME}'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env', 'dist/apps/tg-web/.env.local']
    env:
      - 'VITE_BOT_USERNAME=${_VITE_BOT_USERNAME}'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: COPY-STUFF
    entrypoint: bash
    args:
      - '-e'
      - '-c'
      - |
        cp apps/tg-web/app.yaml dist/apps/tg-web/app.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
    dir: 'dist/apps/tg-web'

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" --service="tg-web" | tail -n +40 | xargs -r gcloud app versions delete --quiet

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
