runtime: nodejs20
instance_class: F2
service: tg-web

automatic_scaling:
  min_idle_instances: 1
  min_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto
    secure: always
