runtime: nodejs20
service: tg-api

instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_instances: 1

inbound_services:
  - warmup

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /.*
    secure: always
    script: auto
