export enum ConfigKeys {
  ApiKey = 'X_API_KEY',
  ClaimImageUrl = 'CLAIM_IMAGE_URL',
  ClaimWebUrl = 'CLAIM_WEB_URL',
  CommunityUrl = 'COMMUNITY_URL',
  DBDatabase = 'DB_DATABASE',
  DBHost = 'DB_HOST',
  DBPassword = 'DB_PASSWORD',
  DBPort = 'DB_PORT',
  DBUsername = 'DB_USERNAME',
  Env = 'ENVIRONMENT',
  FartyClawApiUrl = 'FARTY_CLAW_API_URL',
  MainImageUrl = 'MAIN_IMAGE_URL',
  Salt = 'SALT',
  TelegramApiKey = 'TELEGRAM_API_KEY',
  WebUrl = 'WEB_URL',
  XUrl = 'X_URL',
}
