runtime: nodejs20
service: api

instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  min_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /.*
    secure: always
    script: auto
