runtime: nodejs20
service: api

instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  min_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /.*
    secure: always
    script: auto

vpc_access_connector:
  name: projects/farty-bera-420304/locations/us-east1/connectors/api-connector
  egress_setting: all-traffic
