runtime: nodejs20
service: backend

instance_class: F2

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0

inbound_services:
  - warmup

handlers:
  - url: /.*
    secure: always
    script: auto

vpc_access_connector:
  name: projects/farty-bera-420304/locations/us-east1/connectors/appengine-farty-connector
